[functions]
  directory = "functions"

[build]
  functions = "dist/server"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"